apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: client-onboarding-external-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: client-onboarding-secrets
    creationPolicy: Merge
    template:
      mergePolicy: Merge
  data:
  - secretKey: IDENTITY_POOL_ID
    remoteRef:
      key: dev_kinesis_credentials
      property: identity_pool_id
  - secretKey: KINESIS_STREAM_NAME
    remoteRef:
      key: dev_kinesis_credentials
      property: kinesis_stream
  - secretKey: AWS_REGION_NAME
    remoteRef:
      key: dev_kinesis_credentials
      property: region
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: client-onboarding-ssm-external-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: client-onboarding-secrets
    creationPolicy: Merge
    template:
      mergePolicy: Merge
  data:
  - secretKey: MAINTENANCE_KEY
    remoteRef:
      key: MAINTENANCE_KEY-dev