apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ngliveness-external-secret
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ngliveness-secrets
    creationPolicy: Merge
    template:
      mergePolicy: Merge
  data:
  - secretKey: CLIENT_ID
    remoteRef:
      key: LIVENESS_AUTH_CLIENT_TEST
      property: LIVENESS_AUTH_CLIENT_ID
  - secretKey: CLIENT_SECRET
    remoteRef:
      key: LIVENESS_AUTH_CLIENT_TEST
      property: LIVENESS_AUTH_CLIENT_SECRET
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ngliveness-ssm-external-secret
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: ngliveness-secrets
    creationPolicy: Merge
    template:
      mergePolicy: Merge
  data:
  - secretKey: DB_URI
    remoteRef:
      key: DB_URI-authorization-qa
  - secretKey: RABBIT_MQ_URI
    remoteRef:
      key: RABBIT_MQ_URI-qa
  - secretKey: REDIS_URI
    remoteRef:
      key: REDIS_URI-qa
