apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otp-external-secrets
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: otp-secrets
    creationPolicy: Merge
    template:
      mergePolicy: Merge
  data:
  - secretKey: SSL_KEY
    remoteRef:
      key: qa-internal-services-ssl-key
  - secretKey: SSL_CERT
    remoteRef:
      key: qa-internal-services-ssl-cert
  - secretKey: SSL_KEY_PASSWORD
    remoteRef:
      key: qa-internal-services-ssl-key-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otp-ssm-external-secret
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: otp-secrets
    creationPolicy: Merge
    template:
      mergePolicy: Merge
  data:
  - secretKey: STORAGE_URL
    remoteRef:
      key: DB_URI-otp-qa
