apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: liveness-injection-detection-scaledobject
  namespace: app
spec:
  scaleTargetRef:
    name: liveness-injection-detection
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 1
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "60"
  - type: memory
    metadata:
      type: Utilization
      value: "70"
