apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-services-sa
  namespace: app
  labels:
    app: shared-infrastructure
    environment: qa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::495947449196:role/app-services-role
