apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ngocr-external-secret
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ngocr-secrets
    creationPolicy: Merge
    template:
      mergePolicy: Merge
  data:
  - secretKey: IDENTITY_POOL_ID
    remoteRef:
      key: dev_kinesis_credentials
      property: identity_pool_id
  - secretKey: KINESIS_STREAM_NAME
    remoteRef:
      key: dev_kinesis_credentials
      property: kinesis_stream
  - secretKey: CLIENT_ID
    remoteRef:
      key: OCR_AUTH_CLIENT
      property: OCR_AUTH_CLIENT_ID
  - secretKey: CLIENT_SECRET
    remoteRef:
      key: OCR_AUTH_CLIENT
      property: OCR_AUTH_CLIENT_SECRET
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ngocr-ssm-external-secret
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: ngocr-secrets
    creationPolicy: Merge
    template:
      mergePolicy: Merge
  data:
  - secretKey: DB_URI
    remoteRef:
      key: DB_URI-auth-eks-dev
  - secretKey: RABBIT_MQ_URI
    remoteRef:
      key: RABBIT_MQ_URI-dev
  - secretKey: REDIS_URI
    remoteRef:
      key: REDIS_URI-dev
