apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: video-statement-scaledobject
  namespace: app
spec:
  scaleTargetRef:
    name: video-statement
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 1
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "70"
  - type: memory
    metadata:
      type: Utilization
      value: "80"
