apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: facesplit-external-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: facesplit-secrets
    creationPolicy: Merge
    template:
      mergePolicy: Merge
  data:
  - secretKey: S3_ACCESS_KEY
    remoteRef:
      key: S3_KEYS
      property: ACCESS_KEY
  - secretKey: S3_SECRET_KEY
    remoteRef:
      key: S3_KEYS
      property: SECRET_KEY
  - secretKey: AWS_REGION
    remoteRef:
      key: S3_KEYS
      property: AWS_REGION
  - secretKey: DATABASE_PASS
    remoteRef:
      key: rds_credentials_dev
      property: password
  - secretKey: DATABASE_URL
    remoteRef:
      key: rds_credentials_dev
      property: DATABASE_URL
  - secretKey: DATABASE_USERNAME
    remoteRef:
      key: rds_credentials_dev
      property: username
