apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: otp-scaledobject
  namespace: app
spec:
  scaleTargetRef:
    name: otp
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 2
  maxReplicaCount: 3
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "80"
  - type: memory
    metadata:
      type: Utilization
      value: "90"
