apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: console-external-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: console-secrets
    creationPolicy: Merge
    template:
      mergePolicy: Merge
  data:
  - secretKey: CAPTCHA_JS_SCRIPT
    remoteRef:
      key: DEV_CAPTCHA_FRONTED
      property: CAPTCHA_JS_SCRIPT
  - secretKey: CAPTCHA_API_KEY
    remoteRef:
      key: DEV_CAPTCHA_FRONTED
      property: CONSOLE_CAPTCHA_API_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: console-ssm-external-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: console-secrets
    creationPolicy: Merge
    template:
      mergePolicy: Merge
  data:
  - secretKey: MAINTENANCE_KEY
    remoteRef:
      key: MAINTENANCE_KEY-dev
