apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ocr-external-secret
  namespace: app
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ocr-secrets
  data:
  - secretKey: AUTH_CLIENT_ID
    remoteRef:
      key: OCR_AUTH_V3_TEST
      property: AUTH_CLIENT_ID
  - secretKey: AUTH_CLIENT_SECRET
    remoteRef:
      key: OCR_AUTH_V3_TEST
      property: AUTH_CLIENT_SECRET
  - secretKey: JWT_SECRET_KEY
    remoteRef:
      key: OCR_JWT_SECRET_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ocr-ssm-external-secret
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: ocr-secrets
    creationPolicy: Merge
    template:
      mergePolicy: Merge
  data:
  - secretKey: DB_URI
    remoteRef:
      key: DB_URI-authorization-qa
