apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: liveness-presentation-detection-external-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: liveness-presentation-detection-secrets
    creationPolicy: Merge
    template:
      mergePolicy: Merge
  data:
  - secretKey: SSL_KEY
    remoteRef:
      key: dev-eks-internal-services-ssl-key
  - secretKey: SSL_CERT
    remoteRef:
      key: dev-eks-internal-services-ssl-cert
  - secretKey: SSL_KEY_PASSWORD
    remoteRef:
      key: dev-eks-internal-services-ssl-key-password
