apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authorization-external-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: authorization-secrets
    creationPolicy: Merge
    template:
      mergePolicy: Merge
  data:
  - secretKey: SSL_KEY
    remoteRef:
      key: dev-eks-internal-services-ssl-key
  - secretKey: SSL_CERT
    remoteRef:
      key: dev-eks-internal-services-ssl-cert
  - secretKey: SSL_KEY_PASSWORD
    remoteRef:
      key: dev-eks-internal-services-ssl-key-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authorization-ssm-external-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: authorization-secrets
    creationPolicy: Merge
    template:
      mergePolicy: Merge
  data:
  - secretKey: DB_URI
    remoteRef:
      key: DB_URI-auth-eks-dev
  - secretKey: MAINTENANCE_KEY
    remoteRef:
      key: MAINTENANCE_KEY-dev
