apiVersion: v1
kind: Secret
metadata:
  name: scanovate-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: ssh://git@github.com:pazfr/Helm-lab.git
  sshPrivateKey: |

