apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: liveness-external-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: liveness-secrets
    creationPolicy: Merge
    template:
      mergePolicy: Merge
  data:
  - secretKey: JWT_SECRET_KEY
    remoteRef:
      key: INJECTION_DETECTION_KEY
  - secretKey: KINESIS_STREAM_NAME
    remoteRef:
      key: dev_kinesis_credentials
      property: kinesis_stream
  - secretKey: IDENTITY_POOL_ID
    remoteRef:
      key: dev_kinesis_credentials
      property: identity_pool_id
  - secretKey: AUTH_CLIENT_ID
    remoteRef:
      key: LIVENESS_AUTH_V3_DEV
      property: AUTH_CLIENT_ID
  - secretKey: AUTH_CLIENT_SECRET
    remoteRef:
      key: LIVENESS_AUTH_V3_DEV
      property: AUTH_CLIENT_SECRET
